### ISSUE TITLE
gh-pages branch needs manual updating

### ISSUE THREAD

**Issue by jayvdb** [duyetdev/bruteforce-database#6]
`gh-pages`'s `index.html` is not updated.  Ideally the `gh-pages` branch is automatically built from the list in the README.md .

Note also that it is currently inaccessible due to https://github.com/duyetdev/duyetdev.github.io/issues/2

**Comment by duyetdev** [comment]
I just have move the static page to `master` branch to keep it up to date. many thank thanks :D
